config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/index'
  get 'static_pages/about'
  get '/signup' => 'static_pages#index', :as => :signup

  get 'pins/images' => 'pins#parseimages'
  post 'pins/parseimages'
  get 'pins/finish' => 'pins#comfirmpin' , :as => :comfirmpin
  get 'u/:username' => 'users#show', :as => :userprofile

  devise_for :users
  resources :users
  resources :pins
  resources :users do
    resources :pins
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  require "open-uri"
  belongs_to :user
  
  attr_accessor :img_url
  has_attached_file :image, :styles => { :medium => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  def img_from_url(url)
    self.image = open(url)
  end
    
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pins
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationship, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationship, source: :follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, :presence => TRUE
  validates_uniqueness_of :username


  #follow a user
  def follow(other_user)

    active_relationships.create(followed_id: other_user.id)

  end

  #unfollow a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #return true if following user
  def following?(other_user)
    following.include?(other_user)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  require 'rubygems'
  require 'nokogiri'
  require 'open-uri'


  def index
    if params[:search].present?
      @pins = Pin.where("tittle LIKE ? OR body LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").paginate(:page => params[:page],:per_page => 3).order("created_at DESC")
      render 'search'
    else
      @user_ids = Relationship.where(:follower_id => current_user.id).pluck(:followed_id)
      @user_ids << current_user.id
      @pins = Pin.where(:user_id => @user_ids).paginate(:page => params[:page],:per_page => 3).order("created_at DESC")
    end
  end

  def show
    @pin = Pin.find(params[:id])
   end


  def new
    @pin = Pin.new
  end

  def create
    if params.has_key?(:commit)
      if params[:commit] == "Continue"
        return redirect_to :action => "parseimages", :url=> params[:pin][:img_url]
      end
    end

    @pin = current_user.pins.build(pin_params)

    if params.has_key?(:web_image_url)
      @pin.imgurl = params[:web_image_url]
      @pin.img_from_url(params[:web_image_url])
    end

    if @pin.save
      redirect_to @pin
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    @pin = Pin.find(params[:id])

    if @pin.update(pin_params)
      redirect_to @pin
    else
      render 'edit'
    end
  end

  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
    redirect_to root_path
  end


  def parseimages
    if params.has_key?(:final_url)
      return redirect_to :action => "comfirmpin", :url=> params[:final_url]
    end

    @images = []
    url = URI.parse((params[:url]))
    page = open(url)

    if page.content_type.to_s.include? "image"
      return redirect_to :action => "comfirmpin", :url=> params[:url]
    else
      page = Nokogiri::HTML(page)
      page.xpath("//img").each do |l|
        img = l.attr('src')
        @images << img
      end
    end
  end

  def comfirmpin
    @selectedpinurl = params[:url]
  end

  private
  def pin_params
    params.require(:pin).permit(:tittle, :body, :image, :imgurl)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to userprofile_path(:username => user.username)
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to userprofile_path(:username => user.username)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to pins_path
    else
      redirect_to  signup_path
    end
  end

  def about

  end
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(username: params[:username])
    @pins = Pin.where(:user_id => @user.id).paginate(:page => params[:page],:per_page => 3).order("created_at DESC")

  end
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Copyright <a href="http://upalela.com/">Upalela</a> 2015</small>
  <nav>
    <ul>
      <li><%= link_to "About", static_pages_about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "pinIT", root_path, id: "logo" %>
      </div>

	  <% if user_signed_in? %>
      <%= form_tag pins_path,class:"navbar-form navbar-left", method: :get do %>
          <div class="form-group">
        <%= text_field_tag :search, params[:search], placeholder: 'Find', type: :search, class:"form-control" %><%= submit_tag 'Search', class:"btn btn-default" %></div>
      <% end %>
    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">

              <li> <%= link_to new_pin_path do %><span class="glyphicon glyphicon-plus"></span> <% end %> </li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.username %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                </ul>
              </li>

              <% else %>
    		  	<div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav navbar-right">
               		 	<li><%= link_to new_user_registration_path, :class => 'navbar-link'  do%>Signup<% end %></li>
                	 	<li><%= link_to new_user_session_path, :class => 'navbar-link' do %>Login<% end %></li>
					</ul>
				</div>
         <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <title><%= yield(:title) %> | PinIT app.</title>
  <%= stylesheet_link_tag    'application', media: 'all',
      'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
    <%= render 'layouts/header' %>


    <div class="container">
      <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/pins/_feed.html.erb
<% @pins.each do |p| %>
	<h4><%= link_to p do %><%=p.tittle%><% end %></h4>
	<%= image_tag p.image.url(:medium) %><br>
	<%= p.body %>
	<p><% if p.user.username != current_user.username %>
	      <%= link_to pins_path(:pin => {:tittle => p.tittle, :body => p.body},  :web_image_url => p.imgurl), :method => 			:create  do %>
	  <span class="glyphicon glyphicon-repeat"></span> <% end %>
	  <% end %>
	  Created by <%= link_to p.user.username , userprofile_path(:username => p.user.username) %></p>
	<br>

<% end %>
<%= will_paginate @pins %>

app/views/pins/comfirmpin.html.erb
<% provide(:title, "Add text and description") %>

<%= form_for :pin, :url => pin_path(:pin) do |f| %>

  <p class="final_image" >
    <%= image_tag @selectedpinurl %><br>
    <%= hidden_field_tag : @selectedpinurl %>
	</p>
    <p>
      <%= f.label :tittle %><br>
      <%= f.text_field :tittle, :required => true, :placeholder => "Choose a tittle." %>
    </p>

    <p>
      <%= f.label "Description" %><br>
      <%= f.text_area :body, :required => true,  :placeholder => "Write a bit about the image." %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/pins/index.html.erb
<% provide(:title, "My feed") %>
<center>
    <%= render partial: "feed", object: @pins  %>
</center>

app/views/pins/new.html.erb
<% provide(:title, "Create a new pin") %>

<h4>Upload an image from your computer. </h4>

<%= form_for @pin do |f| %>
    <p>
      <%= f.file_field :image, :required => true %>
    </p>

    <p>
      <%= f.label :tittle %><br>
      <%= f.text_field :tittle, :required => true, :placeholder => "Choose a tittle." %>
    </p>

    <p>
      <%= f.label "Description" %><br>
      <%= f.text_area :body, :required => true, :placeholder => "Write a bit about the image." %>
    </p>

    <p>
      <%= f.submit "Save pin" %>
    </p>
<% end %>

<br><br>
<h4>Or pick an image from the web.</h4>

<%= form_for @pin do |f| %>
	<p>
		<%=f.url_field :img_url, :required => true, :placeholder => "Insert your link here." %>
	</p>

	<p>
		<%= f.submit "Continue" %>
	</p>

<% end %>

app/views/pins/parseimages.html.erb
<% provide(:title, "Choose an image") %>

<% @images.each do |p| %>
        <%= image_tag p %><br>
        <%= link_to "Pin", comfirmpin_path(:url => p) %>
<% end %>

app/views/pins/search.html.erb
<% provide(:title, "Your results") %>
<center>
	<%= render partial: "feed", object: @pins  %>
</center>

app/views/pins/show.html.erb
<% provide(:title, "Pin") %>


<p>
	<%= image_tag @pin.image.url(:medium) %>
</p>
<p>
  <strong>Title:</strong>
  <%= @pin.tittle %>
</p>

<p>
  <strong>Text:</strong>
  <%= @pin.body %>
</p>
<p>
  <%= link_to "delete", pin_path, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<p>Created by <%= link_to @pin.user.username , userprofile_path(:username => @pin.user.username) %></p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>


<body>
<h1>About</h1>
<p>About PINit</p>

.....
something
....

</body>

app/views/static_pages/home.html.erb
<% provide(:title, "Welcome and sign up/sign in.") %>

<body>
    <% if user_signed_in? %>
        <h1>Welcome to pinIT</h1>
        <p>
          Here are your pins.....
        </p>
    <% else %>
        Please sign up or sign in.

    <% end %>

</body>

app/views/static_pages/index.html.erb
<% provide(:title, "Welcome") %>


<h1>Welcome to PinIT.</h1>
<p><%= link_to new_user_registration_path, :class => "btn btn-default" do%>Signup<% end %>
<p><%= link_to new_user_session_path, :class => "btn btn-default" do %>Login<% end %></p>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
    <% end %>

app/views/users/_follow_form.html.erb
    <div id="follow_form">
      <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
    html: { method: :delete }) do |f| %>
<%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.username , userprofile_path(:username => user.username) %>

</li>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<br>
<br>
Stats:
<section class="stats">
  <%= render 'stats' %>
</section>
<br>
<% if user_signed_in? %>
    <%if @user.username != current_user.username %>
        <%= render 'follow_form' %>

    <% end %>
<% end %>

<%= render partial: "pins/feed", object: @pins  %>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">

      <h1><%= @user.username %></h1>
    </section>
    <section class="stats">
      <%= render 'stats' %>

    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users follow">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
    <% end %>
  </div>
</div>